global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'gateway'
    static_configs:
      - targets: ['graphql-gateway:9200']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:9201']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product_service:9202']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order_service:9203']